/*
    Dependes on .mem file which is generated by the assembler. See the assembler in 
    ~/tb/common/riscv_assembler.py for more details.
*/

module instruction_memory (
    input  logic [31:0] addr,
    output logic [31:0] data
);
    logic [31:0] mem [0:1023];  // 1024 words of memory

    initial begin
        $readmemb("instruction_memory.mem", mem);
    end

    assign data = mem[addr[31:2]];  // Word-aligned access

endmodule